# Generated by Django 5.1.3 on 2026-08-30 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(blank=True, choices=[('ук', 'Управляющая компания'), ('подряд', 'Подрядчик')], default=None, max_length=20, null=True, verbose_name='Тип компании')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование компании')),
                ('legal_name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Полное наименование')),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использутся')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование локации')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='WorkSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование рабочей системы')),
                ('pictogram', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Пиктограмма')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использутся')),
            ],
            options={
                'verbose_name': 'Рабочая система',
                'verbose_name_plural': 'Рабочие системы',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование участка')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.location', verbose_name='Локация'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование улицы')),
                ('legal_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Правильное наименование улицы')),
                ('c1_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Наименование улицы в 1С')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использутся')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Объект')),
                ('house', models.CharField(default=None, max_length=15, null=True, verbose_name='Дом')),
                ('lon', models.FloatField(blank=True, default=None, null=True, verbose_name='lon')),
                ('lat', models.FloatField(blank=True, default=None, null=True, verbose_name='lat')),
                ('channelid', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Ид. телеграмм канала')),
                ('square', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Площадь')),
                ('flat_count', models.IntegerField(default=0, verbose_name='Кол-во квартир')),
                ('floor_count', models.IntegerField(default=0, verbose_name='Кол-во этажей')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='buildings/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
                ('source', models.JSONField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.company', verbose_name='Компания')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.location', verbose_name='Локация')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dict.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('post', models.CharField(choices=[('boss', 'Генеральный'), ('secretary', 'Секретарь'), ('chief', 'Начальник участка'), ('itr', 'ИТР'), ('admin', 'Административный'), ('disp', 'Диспетчер участка'), ('master', 'Мастер участка'), ('worker', 'Рабочий участка')], default='worker', max_length=20, verbose_name='Должность')),
                ('deleted', models.BooleanField(default=False, verbose_name='Уволен?')),
                ('phone', models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='Телеграмм')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dict.company', verbose_name='Компания')),
                ('district', models.ManyToManyField(blank=True, default=None, null=True, to='dict.district', verbose_name='Участок')),
                ('district_main', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_main', to='dict.district', verbose_name='Основной участок')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('worksystem', models.ManyToManyField(blank=True, default=None, to='dict.worksystem', verbose_name='Рабочая система')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('name',),
            },
        ),
    ]
