# Generated by Django 5.1.3 on 2026-08-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetInCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.company', verbose_name='Компания')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dict.street', verbose_name='Улица')),
            ],
        ),
    ]
