# Generated by Django 5.1.3 on 2026-08-31 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_streetincompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streetincompany',
            options={'ordering': ('street',), 'verbose_name': 'Обслуживаемые улицы', 'verbose_name_plural': 'Обслуживаемые улицы'},
        ),
    ]
