# Generated by Django 5.1.3 on 2026-09-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='company', verbose_name='Логотип'),
        ),
    ]
