# Generated by Django 5.1.3 on 2026-09-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Описание')),
                ('worksystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.worksystem', verbose_name='Рабочая система')),
            ],
            options={
                'verbose_name': 'Стандартное описание заявки',
                'verbose_name_plural': 'Стандартные описания заявок',
            },
        ),
    ]
