# Generated by Django 5.1.3 on 2026-08-31 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dict', '0003_alter_streetincompany_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Ид')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('color', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Цвет')),
                ('pos', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('сompleted', models.BooleanField(default=False, verbose_name='Признак завершения')),
            ],
            options={
                'verbose_name': 'Состояние заявки',
                'verbose_name_plural': 'Состояния заявок',
                'ordering': ('pos',),
            },
        ),
        migrations.CreateModel(
            name='Numbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Суффикс')),
                ('prefix', models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Префикс')),
                ('current_number', models.IntegerField(default=1, verbose_name='Текущий номер')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.district', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Нумерация',
                'verbose_name_plural': 'Нумерация',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата изменения')),
                ('last_printed_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата последней печати')),
                ('number', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Номер')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата заявки')),
                ('ordertype', models.CharField(choices=[('houses', 'Общедомовые'), ('flats', 'Поквартирные'), ('paid', 'Платная'), ('repair', 'Текущий ремонт'), ('household', 'Хознужды'), ('emergency', 'Аварийная')], default='houses', max_length=20, verbose_name='Тип')),
                ('priority', models.CharField(choices=[('emergency', 'Аварийная'), ('urgent', 'Срочная'), ('current', 'Текущая')], default='current', max_length=20, verbose_name='Приоритет')),
                ('sourcetype', models.CharField(choices=[('disp', 'Диспетчер'), ('site', 'Сайт'), ('max', 'Max'), ('auto', 'Автозаявка')], default='disp', max_length=20, verbose_name='Источник')),
                ('citizen', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Телефон')),
                ('house', models.CharField(default=None, max_length=15, null=True, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Квартира')),
                ('entrance', models.IntegerField(blank=True, default=None, null=True, verbose_name='Подъезд')),
                ('floor', models.IntegerField(blank=True, default=None, null=True, verbose_name='Этаж')),
                ('plan_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата план')),
                ('plan_period', models.CharField(blank=True, choices=[('until', 'До полудня'), ('after', 'После полудня'), ('during', 'В течениe дня')], default='during', max_length=20, null=True, verbose_name='Период план')),
                ('description', models.TextField(max_length=500, verbose_name='Описание заяки')),
                ('fact_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Фактическая дата выполнения')),
                ('fact_start_work_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Фактическое время начала выполнения')),
                ('fact_description', models.TextField(blank=True, default=None, null=True, verbose_name='Фактическое описание')),
                ('orderid', models.IntegerField(blank=True, default=None, null=True, verbose_name='Внешний ид')),
                ('summa', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Сумма')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('building', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.building', verbose_name='Объект')),
                ('company_exec', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_exec', to='dict.company', verbose_name='Подрядчик')),
                ('company_owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_owner', to='dict.company', verbose_name='УК')),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.district', verbose_name='Участок')),
                ('employee', models.ManyToManyField(blank=True, to='dict.employee', verbose_name='Исполнитель')),
                ('master', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_user', to='dict.employee', verbose_name='Мастер')),
                ('street', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.street', verbose_name='Улица')),
                ('worksystem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.worksystem', verbose_name='Рабочая система')),
                ('state', models.ForeignKey(blank=True, default='accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.orderstate', verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='FotosInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Описание')),
                ('foto', models.ImageField(blank=True, default=None, null=True, upload_to='fotos/', verbose_name='Фото')),
                ('max_token', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('max_url', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Фото в заявке',
                'verbose_name_plural': 'Фото в заявке',
            },
        ),
    ]
