# Generated by Django 5.1.3 on 2026-09-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('dict', '0003_alter_streetincompany_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbering',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('emergency', '❗Аварийная'), ('urgent', 'Срочная'), ('current', 'Текущая')], default='current', max_length=20, verbose_name='Приоритет'),
        ),
    ]
