# Generated by Django 5.1.3 on 2026-09-02 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_numbering_company_alter_order_priority'),
        ('dict', '0003_alter_streetincompany_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictInBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.building', verbose_name='Объект')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.company', verbose_name='Компания')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.district', verbose_name='Участок')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSystemInBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.building', verbose_name='Объект')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.company', verbose_name='Компания')),
                ('company_exec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_exec_building', to='dict.company', verbose_name='Компания')),
                ('worksystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.worksystem', verbose_name='Рабочая система')),
            ],
        ),
    ]
