# Generated by Django 5.1.3 on 2026-09-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_districtinbuilding_worksysteminbuilding'),
        ('dict', '0003_alter_streetincompany_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksysteminbuilding',
            name='worksystem',
        ),
        migrations.AddField(
            model_name='worksysteminbuilding',
            name='worksystem',
            field=models.ManyToManyField(to='dict.worksystem', verbose_name='Рабочая система'),
        ),
    ]
