# Generated by Django 5.1.3 on 2026-09-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_worksysteminbuilding_worksystem_and_more'),
        ('dict', '0003_alter_streetincompany_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksysteminbuilding',
            name='building',
        ),
        migrations.AddField(
            model_name='worksysteminbuilding',
            name='building',
            field=models.ManyToManyField(to='dict.building', verbose_name='Объект'),
        ),
    ]
