# Generated by Django 5.1.3 on 2026-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_worksysteminbuilding_building_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtinbuilding',
            options={'verbose_name': 'Участки УК', 'verbose_name_plural': 'Участки УК'},
        ),
        migrations.AlterModelOptions(
            name='worksysteminbuilding',
            options={'verbose_name': 'Закрепления подрядчика за объектами', 'verbose_name_plural': 'Закрепления подрядчика за объектами'},
        ),
        migrations.AddField(
            model_name='order',
            name='master_text',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Мастер_'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_text',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='План текст'),
        ),
        migrations.AddField(
            model_name='order',
            name='worker_text',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Исполнитель_'),
        ),
    ]
