# Generated by Django 5.1.3 on 2026-09-16 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_districtinbuilding_options_and_more'),
        ('dict', '0005_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disconnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('number', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Номер')),
                ('start_disconnect', models.DateTimeField(verbose_name='Дата начала отключения')),
                ('plan_connection_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Плановая дата подключения')),
                ('fact_connection_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Фактическая дата подключения')),
                ('description', models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Описание')),
                ('connected', models.BooleanField(default=False, verbose_name='Подключено?')),
                ('sender', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Ответсвенный от компании')),
                ('disconnection_type', models.CharField(blank=True, choices=[('Отключение', 'Отключение'), ('Аварийное', 'Аварийное'), ('Ухудшение', 'Ухудшение'), ('Информация', 'Информация')], default='Отключение', max_length=50, null=True, verbose_name='Тип')),
                ('source', models.CharField(blank=True, choices=[('Входящее', 'Входящее'), ('Исходящее', 'Исходящее'), ('Внутренее', 'Внутренее')], default='Входящее', max_length=50, null=True, verbose_name='Источник')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('data', models.JSONField(blank=True, default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('building', models.ManyToManyField(blank=True, default=None, null=True, to='dict.building', verbose_name='Объекты')),
                ('company_exec', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disc_company_exec', to='dict.company', verbose_name='Подрядчик')),
                ('company_owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disc_company_owner', to='dict.company', verbose_name='УК')),
                ('worksystem', models.ManyToManyField(default=None, to='dict.worksystem', verbose_name='Рабочая система')),
            ],
            options={
                'verbose_name': 'Отключение',
                'verbose_name_plural': 'Отключения',
            },
        ),
    ]
