# Generated by Django 5.1.3 on 2026-09-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_disconnect'),
        ('dict', '0006_standarddescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtinbuilding',
            options={'verbose_name': 'Закрепление участков УК за домами', 'verbose_name_plural': 'Закрепление участков УК за домами'},
        ),
        migrations.AlterField(
            model_name='disconnect',
            name='sender',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Ответственный от подрятчика'),
        ),
        migrations.RemoveField(
            model_name='districtinbuilding',
            name='building',
        ),
        migrations.AddField(
            model_name='districtinbuilding',
            name='building',
            field=models.ManyToManyField(to='dict.building', verbose_name='Объекты'),
        ),
    ]
